export const constants = {
    SET_TOTAL_RECORD: 'SET_TOTAL_RECORD',
    IS_LOADING: 'IS_LOADING',
    IS_UPDATE_STATE: 'IS_UPDATE_STATE',
    IS_META: 'IS_META'
};

export const portfoliosActionType = {
    FETCH_PORTFOLIOS: 'FETCH_PORTFOLIOS',
    FETCH_PORTFOLIOS_ALL: 'FETCH_PORTFOLIOS_ALL',
    FETCH_PORTFOLIO: 'FETCH_PORTFOLIO',
    ADD_PORTFOLIO: 'ADD_PORTFOLIO',
    UPDATE_PORTFOLIO: 'UPDATE_PORTFOLIO',
    DELETE_PORTFOLIO: 'DELETE_PORTFOLIO',
};